### PR TITLE
glance version string

### PR DESCRIPTION
**Pull request by ccollicutt**
I'm not sure this is the right solution for this module, but in my environment I had to make this small change.

### CODE REVIEW

**Comment by lorin** [comment]
Hmmm, it looks like the internal API changed. I'd like this module to be able to support both older and newer versions of glance. Could you wrap your change in a try block, and if an AttributeError is thrown, call the original code? This would ensure backwards compatibility.

**Comment by lorin** [comment]
Also, can you let me know which version of OpenStack you're running?

**Comment by ccollicutt** [comment]
How's that?

**Comment by lorin** [comment]
Perfect, thanks.

**Comment by ccollicutt** [comment]
Cool thanks! Oh and sorry I forgot to mention what version of OpenStack -- Juno on Ubuntu 14.04 from the Ubuntu Cloud Archive.

**Pull request merged**
